version: "3.9"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_adopet
    restart: always
    ports:
      - 65432:5432
    environment:
      - POSTGRES_USER=bigarelli
      - POSTGRES_PASSWORD=biga
      - POSTGRES_DB=adopet
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: adopetCP
    restart: always
    ports:
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local
